import {NgModule} from '@angular/core';
import {
    IgxButtonModule,
    IgxDatePickerModule, IgxGridModule,
    IgxIconModule,
    IgxInputGroupModule,
    IgxLayoutModule,
    IgxNavbarModule,
    IgxNavigationDrawerModule,
    IgxRadioModule, IgxRippleModule, IgxSwitchModule,
    IgxTimePickerModule,
    IgxToastModule,
    IgxToggleModule,
    IgxDropDownModule,
    IgxChipsModule,
    IgxCarouselModule,
    IgxComboModule,
    IgxNavigationModule,
    IgxProgressBarModule,
    IgxAvatarModule,
    IgxFilterModule,
    IgxBadgeModule,
    IgxButtonGroupModule,
    IgxDialogModule,
    IgxCalendarModule,
    IgxSnackbarModule,
    IgxCardModule,
    IgxListModule,
    IgxCheckboxModule,
    IgxSliderModule,
    IgxBottomNavModule,
    IgxTabsModule,
    IgxForOfModule,
    IgxMaskModule,
    IgxCsvExporterService,
    IgxExcelExporterService,
    IgxOverlayService, IgxExpansionPanelModule, IgxTooltipModule, IgxSelectModule
} from 'igniteui-angular';



const MODULES = [
  IgxToastModule,
  IgxInputGroupModule,
  IgxButtonModule,
  IgxDatePickerModule,
  IgxTimePickerModule,
  IgxIconModule,
  IgxGridModule,
  IgxLayoutModule,
  IgxToggleModule,
  IgxNavigationDrawerModule,
  IgxRippleModule,
  IgxNavbarModule,
  IgxRadioModule,
  IgxSwitchModule,
  IgxDropDownModule,
  IgxInputGroupModule,
  IgxChipsModule,
  IgxCarouselModule,
  IgxComboModule,
  IgxLayoutModule,
  IgxRadioModule,
  IgxSwitchModule,
  IgxNavigationModule,
  IgxNavigationDrawerModule,
  IgxProgressBarModule,
  IgxAvatarModule,
  IgxFilterModule,
  IgxBadgeModule,
  IgxButtonModule,
  IgxButtonGroupModule,
  IgxRippleModule,
  IgxIconModule,
  IgxDialogModule,
  IgxDropDownModule,
  IgxDatePickerModule,
  IgxDropDownModule,
  IgxCalendarModule,
  IgxSnackbarModule,
  IgxCardModule,
  IgxListModule,
  IgxCheckboxModule,
  IgxToastModule,
  IgxSliderModule,
  IgxBottomNavModule,
  IgxTabsModule,
  IgxNavbarModule,
  IgxToggleModule,
  IgxForOfModule,
  IgxMaskModule,
  IgxTimePickerModule,
  IgxInputGroupModule,
    IgxAvatarModule,
    IgxExpansionPanelModule,
    IgxTooltipModule,
    IgxSelectModule,
    IgxComboModule,
];

@NgModule({
  imports: [
    ...MODULES,
  ],
  exports: [
    ...MODULES,
  ],
  providers: [
      IgxCsvExporterService,
      IgxExcelExporterService,
      IgxOverlayService
  ]
})

export class InfragisticsModule {  }
