export class LeadForm {
    LeadID: string;
    p_contact_name: string;
    p_contact_first_name: string;
    p_contact_middle_name: string;
    p_contact_last_name: string;
    p_contact_title: string;
    p_contact_suffix: string;
    p_contact_gender: string;
    p_contact_bday: any;
    p_contact_mobile: string;
    p_contact_home: string;
    p_contact_office: string;
    p_contact_email: string;
    p_contact_email_alternate: string;
    p_contact_job_title: string;
    p_contact_occupation: string;
    s_contact_name: string;
    s_contact_first_name: string;
    s_contact_middle_name: string;
    s_contact_last_name: string;
    s_contact_title: string;
    s_contact_suffix: string;
    s_contact_gender: string;
    s_contact_bday: any;
    s_contact_mobile: string;
    s_contact_home: string;
    s_contact_office: string;
    s_contact_email: string;
    s_contact_email_alternate: string;
    s_contact_job_title: string;
    s_contact_occupation: string;
    home_street_address: string;
    home_city: string;
    home_state: string;
    home_zip: string;
    home_country: string;
    search_min_beds: string;
    search_min_baths: string;
    search_min_garage: string;
    search_pool: string;
    search_min_sq_ft: string;
    search_storey: string;
    search_max_sqft: string;
    search_min_lot_sqft: string;
    search_max_lot_sqft: string;
    search_min_year_build: string;
    search_max_year_build: string;

    constructor(formData: any) {
        this.LeadID = formData.LeadID;
        this.p_contact_name = formData.p_contact_name || '';
        this.p_contact_first_name = formData.p_contact_first_name || '';
        this.p_contact_middle_name = formData.p_contact_middle_name || '';
        this.p_contact_last_name = formData.p_contact_last_name || '';
        this.p_contact_title = formData.p_contact_title || '';
        this.p_contact_suffix = formData.p_contact_suffix || '';
        this.p_contact_gender = formData.p_contact_gender || '';
        this.p_contact_bday = formData.p_contact_bday ? new Date(formData.p_contact_bday) : '';
        this.p_contact_mobile = formData.p_contact_mobile || '';
        this.p_contact_home = formData.p_contact_home || '';
        this.p_contact_office = formData.p_contact_office || '';
        this.p_contact_email = formData.p_contact_email || '';
        this.p_contact_email_alternate = formData.p_contact_email_alternate || '';
        this.p_contact_job_title = formData.p_contact_job_title || '';
        this.p_contact_occupation = formData.p_contact_occupation || '';
        this.s_contact_name = formData.s_contact_name || '';
        this.s_contact_first_name = formData.s_contact_first_name || '';
        this.s_contact_middle_name = formData.s_contact_middle_name || '';
        this.s_contact_last_name = formData.s_contact_last_name || '';
        this.s_contact_title = formData.s_contact_title || '';
        this.s_contact_suffix = formData.s_contact_suffix || '';
        this.s_contact_gender = formData.s_contact_gender || '';
        this.s_contact_bday = formData.s_contact_bday ? new Date(formData.s_contact_bday) : '';
        this.s_contact_mobile = formData.s_contact_mobile || '';
        this.s_contact_home = formData.s_contact_home || '';
        this.s_contact_office = formData.s_contact_office || '';
        this.s_contact_email = formData.s_contact_email || '';
        this.s_contact_email_alternate = formData.s_contact_email_alternate || '';
        this.s_contact_job_title = formData.s_contact_job_title || '';
        this.s_contact_occupation = formData.s_contact_occupation || '';
        this.home_street_address = formData.home_street_address || '';
        this.home_city = formData.home_city || '';
        this.home_state = formData.home_state || '';
        this.home_zip = formData.home_zip || '';
        this.home_country = formData.home_country || '';
        this.search_min_beds = formData.search_min_beds || '';
        this.search_min_baths = formData.search_min_baths || '';
        this.search_min_garage = formData.search_min_garage || '';
        this.search_pool = formData.search_pool || '';
        this.search_min_sq_ft = formData.search_min_sq_ft || '';
        this.search_storey = formData.search_storey || '';
        this.search_max_sqft = formData.search_max_sqft || '';
        this.search_min_lot_sqft = formData.search_min_lot_sqft || '';
        this.search_max_lot_sqft = formData.search_max_lot_sqft || '';
        this.search_min_year_build = formData.search_min_year_build || '';
        this.search_max_year_build = formData.search_max_year_build || '';
    }
}
